---
- name: Includes dynamic configuration file
  include_vars: "{{ vars_files }}"
  when: vars_files is defined

- name: sshfs | Install base packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - sshfs
    - supervisor

- name: sshfs | Start supervisor service
  service:
    name: supervisor
    state: started

- name: sshfs | Host files directory stat
  stat:
    path: "{{ sshfs_base_directory }}/{{ sshfs_ssh_hostname }}/{{ sshfs_mount_directory }}"
  register: check_host_file_directory
  when: >
    sshfs_active is defined 
    and sshfs_active == true

- name: sshfs | Prepare host files directory
  file: 
    path: "{{ sshfs_base_directory }}/{{ sshfs_ssh_hostname }}/{{ sshfs_mount_directory }}"
    owner: "{{ sshfs_file_owner }}"
    mode: "{{ sshfs_file_mode }}"
    state: "directory"
    recurse: yes
  when: >
    sshfs_active is defined 
    and sshfs_active == true
    and check_host_file_directory.stat.isdir is defined 
    and not check_host_file_directory.stat.isdir

- name: sshfs | Validate ssh connections
  shell: >
    timeout 5 
    ssh 
    -o StrictHostKeyChecking=no
    -o PasswordAuthentication=no
    -i {{ ssh_config_dir }}/keys/{{ sshfs_ssh_hostname }}/id_rsa
    -F {{ ssh_config_file }}
    {{ sshfs_ssh_hostname }} echo {{ sshfs_return_msg }} 2>/dev/null
  when: >
    ssh_config_dir is defined
    and ssh_config_file is defined
    and sshfs_ssh_hostname is defined
    and sshfs_ssh_options is defined
    and sshfs_active == true
  register: ssh_connections_debug
  ignore_errors: yes

- name: sshfs | Show - debug ssh connections
  debug: 
    msg: "{{ ssh_connections_debug }}"
  when: >
    sshfs_debug is defined 
    and sshfs_debug == true
    and ssh_connections_debug.stdout.find(sshfs_return_msg) != -1

- name: sshfs | Add supervisor configuration.
  template:
    src: "etc/supervisor/conf.d/supervisor_sshfs.conf.j2"
    dest: "{{ item.supervisor_file }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - supervisor_file: "/etc/supervisor/conf.d/supervisor_sshfs_{{ sshfs_ssh_hostname }}.conf"
      supervisor_program_name: "{{ sshfs_supervisor_name }}_{{ sshfs_ssh_hostname }}"
      supervisor_program_cmd: >
        sshfs 
        {{ sshfs_ssh_hostname }}:{{ sshfs_ssh_directory }}
        {{ sshfs_base_directory }}/{{ sshfs_ssh_hostname }}/{{ sshfs_mount_directory }} 
        -F {{ ssh_config_file }} -f

  notify: sshfs - notify | Restart supervisor sshfs
  when: >
    ssh_connections_debug is defined
    and ssh_connections_debug.stdout.find(sshfs_return_msg) != -1

- name: sshfs | Reload supervisor file
  supervisorctl: 
    name: "{{ sshfs_supervisor_name }}_{{ sshfs_ssh_hostname }}"
    state: present
  when: >
    ssh_connections_debug is defined
    and ssh_connections_debug.stdout.find(sshfs_return_msg) != -1


